# Site settings
title:          Running down the rabbit holes
description:    "A map of rabbitholes in my mind that is a work in progress"
url:            "https://belligerent-buffoon.github.io"

# Google Analytics
google_analytics: UA-156077400-1

# Author
author:
  name:         Priyank Gupta
  url:          https://priyaaank.com/
  email:        priyaaank@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
disqus:         belligerentbuffoon